"""initial schema

Revision ID: 94476acce711
Revises: 
Create Date: 2026-09-18 12:23:05.432981

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '94476acce711'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('allowed_radius_meters', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.CheckConstraint('allowed_radius_meters > 0', name=op.f('ck_branches_allowed_radius_meters_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('name', name=op.f('uq_branches_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'EMPLOYEE', name='user_role'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_users_branch_id_branches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_index('ix_users_branch_id', 'users', ['branch_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('check_in_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('check_out_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('check_out_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('check_in_distance_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('check_out_distance_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'LATE', 'LEFT_EARLY', 'ABSENT', 'ON_LEAVE', name='attendance_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_attendances_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('fk_attendances_employee_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendances')),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_attendances_employee_work_date')
    )
    op.create_index('ix_attendances_branch_work_date', 'attendances', ['branch_id', 'work_date'], unique=False)
    op.create_index('ix_attendances_check_in_at', 'attendances', ['check_in_at'], unique=False)
    op.create_index('ix_attendances_employee_id', 'attendances', ['employee_id'], unique=False)
    op.create_index('ix_attendances_status', 'attendances', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_created_at', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('DAY_OFF', 'VACATION', 'SICK', name='leave_type'), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('date_to >= date_from', name=op.f('ck_leaves_date_to_on_or_after_date_from')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_leaves_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('fk_leaves_employee_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaves'))
    )
    op.create_index('ix_leaves_approved_by', 'leaves', ['approved_by'], unique=False)
    op.create_index('ix_leaves_employee_dates', 'leaves', ['employee_id', 'date_from', 'date_to'], unique=False)
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_period_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('grace_period_minutes >= 0', name=op.f('ck_work_schedules_grace_period_minutes_non_negative')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_work_schedules_weekday_between_0_and_6')),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('fk_work_schedules_employee_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_schedules')),
    sa.UniqueConstraint('employee_id', 'weekday', name='uq_work_schedules_employee_weekday')
    )
    op.create_index('ix_work_schedules_employee_id', 'work_schedules', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_schedules_employee_id', table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index('ix_leaves_employee_dates', table_name='leaves')
    op.drop_index('ix_leaves_approved_by', table_name='leaves')
    op.drop_table('leaves')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attendances_status', table_name='attendances')
    op.drop_index('ix_attendances_employee_id', table_name='attendances')
    op.drop_index('ix_attendances_check_in_at', table_name='attendances')
    op.drop_index('ix_attendances_branch_work_date', table_name='attendances')
    op.drop_table('attendances')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_branch_id', table_name='users')
    op.drop_table('users')
    op.drop_table('branches')
    # ### end Alembic commands ###
